version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_USER: anhmantk
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
      - ../docker_data/mariadb:/var/lib/mysql
  php-fpm:
    image: php:5.6-fpm
    volumes:
      - ./www:/var/www
    links:
      - mariadb
      # - elasticsearch
      # - redis
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./www:/var/www
    ports:
      - "80:80"
    links:
      - php-fpm
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: anhmantk
      MYSQL_PASSWORD: 123123
      PMA_HOST: mariadb
    links:
      - mariadb  
  # redis:
  #   image: redis:latest
  #   volumes:
  #     - ../docker_data/redis:/data
  #   ports:
  #     - "6379:6379"
  # elasticsearch:
  #   image: elasticsearch
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"